### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by sp4plm** [ecc1/rfm69#2]
I can't connect DIO0 and CE1 in https://www.adafruit.com/product/3070. There are no pairs.

**Comment by ecc1** [comment]
See https://learn.adafruit.com/adafruit-rfm69hcw-and-rfm96-rfm95-rfm98-lora-packet-padio-breakouts/pinouts

DIO0 is labeled G0 on that breakout board. CE1 is the master's SPI CE1, which connects to the pad labeled CS (chip select) on the breakout board.
