### ISSUE TITLE
issue with port

### ISSUE THREAD

**Issue by sp4plm** [ecc1/rfm69#3]
I have connect PI with RFM69HCW on port /dev/spidev0.1, see picture. The test is OK. But mmtune asks /dev/spidev0.0.
How I can turn mmtune to use /dev/spidev0.1 ?
![term](https://user-images.githubusercontent.com/41417313/55909143-f2c1c600-5be3-11e9-9b81-f95c8b1b7b35.png)
![rasp-rfm69-link](https://user-images.githubusercontent.com/41417313/55909173-010fe200-5be4-11e9-92f3-b6ea7b2c6d02.png)

**Comment by ecc1** [comment]
How did you build the mmtune program? Have you done a "git pull" recently?  "go build" should use the default configuration with spidev0.1 if your repo is up to date

**Comment by sp4plm** [comment]
Hi. 

I used command as recommended in open apps:

$ rm -rf ~/go/src/github.com/ecc1 
$ go get -u -v -tags "rfm69 walrus" github.com/ecc1/medtronic/... 
$ cp -pruv $HOME/go/bin/* /usr/local/bin/ 
$ mv /usr/local/bin/mmtune /usr/local/bin/Go-mmtune

From iPhone
Oleg

**Comment by ecc1** [comment]
That's incorrect. With the wiring you described, you should not use the "walrus" build tag, just "rfm69". Where did you find those instructions? I'd like to get them corrected.
